server:
  port: 8080

spring:
  application:
    name: api-gateway-quickbite

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            # AUTH SERVICE
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**

            # USER SERVICE
            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/users/**

            # MENU SERVICE
            - id: menu-service
              uri: ${MENU_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/menus/**

            # ORDER SERVICE
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/api/ordenes/**

            # PAYMENT SERVICE
            - id: payment-service
              uri: ${PAGOS_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/api/pagos/**

            # NOTIFICATION SERVICE
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/api/notificaciones/**

            # SWAGGER AUTH
            - id: auth-docs
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/auth-docs
              filters:
                - SetPath=/api-docs

            # SWAGGER USER
            - id: user-docs
              uri: ${USER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/user-docs
              filters:
                - SetPath=/api-docs

            # SWAGGER MENU
            - id: menu-docs
              uri: ${MENU_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/menu-docs
              filters:
                - SetPath=/api-docs

            # SWAGGER ORDER
            - id: order-docs
              uri: ${ORDER_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/order-docs
              filters:
                - SetPath=/api-docs

            # SWAGGER PAYMENT
            - id: payment-docs
              uri: ${PAGOS_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/payment-docs
              filters:
                - SetPath=/api-docs

            # SWAGGER NOTIFICATION
            - id: notification-docs
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/notification-docs
              filters:
                - SetPath=/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info