spring.application.name=AuthServiceQuickBite
server.port=8081

# Cambiamos localhost por la variable ${DB_HOST:localhost}
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/quickbite_auth?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=QuickBiteSecretKeyForJwtAuthentication2026SuperSecret
jwt.expiration=86400000


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html