# ===================================================================
# CONFIGURACION GENERAL DEL MICROSERVICIO
# ===================================================================
spring.application.name=UserServiceQuickBite
server.port=8082

# ===================================================================
# CONFIGURACION DE LA BASE DE DATOS (MySQL) - Adaptada para Docker
# ===================================================================
spring.datasource.url=jdbc:mysql://${DB_USER_HOST:localhost}:${DB_USER_PORT:3306}/quickbite_user?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER_USER:root}
spring.datasource.password=${DB_USER_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# CONFIGURACION DE JPA / HIBERNATE
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===================================================================
# CONFIGURACION DE FLYWAY
# ===================================================================
spring.flyway.enabled=false


# Agregar al final de las propiedades de cada microservicio
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html